name: chillers_hub
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ion: ^1.0.0
  cupertino_icons: ^1.0.2
  get: 4.6.1
  animated_theme_switcher: ^2.0.6
  get_storage: ^2.0.3
  google_fonts: ^2.3.1
  flex_color_scheme: ^4.2.0
  lottie: ^1.2.2
  flutter_svg: ^1.0.3
  flutter_spinkit: ^5.1.0
  bitsdojo_window: ^0.1.1+1
  logger: ^1.1.0
  qr_flutter: ^4.0.0
  desktop_window: ^0.4.0
  sliding_up_panel: ^2.0.0+1
  unicons: ^2.1.0
  fluentui_system_icons: ^1.1.162
  just_audio: ^0.9.20
  just_audio_libwinmedia: any
  intl: ^0.17.0
  audio_video_progress_bar: ^0.10.0
  uuid: ^3.0.6
  flutter_blurhash: ^0.6.4
  timeago: ^3.2.2
  url_launcher: ^6.0.20
  responsive_grid: ^2.0.0
  dropdown_button2: ^1.2.2
  eva_icons_flutter: ^3.1.0
  badges: ^2.0.2
  glassmorphism: ^3.0.0
  url_strategy: ^0.2.0
  font_awesome_flutter: ^10.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: 0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_ios: assets/app-icon/icon.png
  image_path_android: assets/app-icon/icon.png
  adaptive_icon_background: assets/app-icon/icon-background.png
  adaptive_icon_foreground: assets/app-icon/icon-forground.png
  ios: true
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/svg/
    - assets/lottie/
    - assets/images/
    - assets/audio/
    - assets/avatars/
    - assets/event/
    - assets/dj/
    - assets/icons/
